import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HeroesComponent } from './heroes/heroes.component';

//import FormsModule
import { FormsModule } from '@angular/forms';
//generated by "ng generate component command"
import { HeroDetailComponent } from './hero-detail/hero-detail.component';

@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent,
    //generated by "ng generate component command"
    HeroDetailComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    //import FormsModule
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
